# Generated by Django 5.2.13 on 2026-06-12 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_options_alter_plan_features_and_more'),
        ('users', '0004_usuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='plan_activado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='plan_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='plan_expira_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
