# Generated by Django 4.1.13 on 2026-05-25 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('duracion_dias', models.PositiveIntegerField(default=30)),
                ('max_Propiedads', models.PositiveIntegerField(default=10)),
                ('max_imagenes', models.PositiveIntegerField(default=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
    ]
