# Generated by Django 4.1.13 on 2026-05-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['precio'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duracion_dias',
            field=models.PositiveIntegerField(default=30, verbose_name='Duración (días)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_imagenes',
            field=models.PositiveIntegerField(default=20, verbose_name='Máximo de Imágenes por Propiedad'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_Propiedads',
            field=models.PositiveIntegerField(default=10, verbose_name='Máximo de Propiedads'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio'),
        ),
    ]
