# Generated by Django 4.1.13 on 2026-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_rename_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.TextField(blank=True, default='[]', verbose_name='Características (JSON)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='¿Es plan destacado?'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_photos',
            field=models.PositiveIntegerField(default=20, verbose_name='Máximo de Fotos por Propiedad'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_properties',
            field=models.PositiveIntegerField(default=10, verbose_name='Máximo de Propiedades'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
