# Generated by Django 5.2.13 on 2026-05-30 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('penthouse', 'Penthouse'), ('local', 'Local Comercial'), ('finca', 'Finca'), ('lote', 'Lote')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('area', models.FloatField()),
                ('habitaciones', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('negociacion', 'En Negociación'), ('vendido', 'Vendido')], default='disponible', max_length=20)),
                ('estrato', models.IntegerField(blank=True, null=True)),
                ('garaje', models.BooleanField(default=False)),
                ('piscina', models.BooleanField(default=False)),
                ('amoblado', models.BooleanField(default=False)),
                ('plan_nombre', models.CharField(default='gratuito', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='properties/')),
                ('es_principal', models.BooleanField(default=False)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='properties.propiedad')),
            ],
        ),
    ]
