# Generated by Django 5.2.13 on 2026-06-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='contacto_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
