# Generated by Django 4.1.13 on 2026-05-26 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0002_alter_plan_options_plan_updated_at_alter_plan_activo_and_more'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='fecha',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email de contacto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre del interesado'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imageninmueble',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='inmuebles', to='plans.plan', verbose_name='Plan de Publicación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('local', 'Local'), ('lote', 'Lote'), ('finca', 'Finca')], max_length=20, verbose_name='Tipo de Inmueble'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='url_video_youtube',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL Video Youtube'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmuebles', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
    ]
