# Generated by Django 5.2.13 on 2026-06-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propiedad_contacto_email_propiedad_contacto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
