# Generated by Django 4.1.13 on 2026-05-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_fecha_favorito_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='whatsapp_contacto',
            field=models.CharField(blank=True, max_length=20, verbose_name='Whatsapp de contacto'),
        ),
    ]
