# Generated by Django 5.2.13 on 2026-05-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_inmueble_whatsapp_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='url_video_youtube',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='amenidades',
            field=models.TextField(blank=True, null=True, verbose_name='Amenidades'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='area',
            field=models.FloatField(default=0, verbose_name='Área en m²'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='banos',
            field=models.IntegerField(default=1, verbose_name='Baños'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='detalles_extra',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles extra'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='habitaciones',
            field=models.IntegerField(default=1, verbose_name='Habitaciones'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='whatsapp_contacto',
            field=models.CharField(max_length=20, verbose_name='Whatsapp de contacto'),
        ),
    ]
