# Generated by Django 5.2.13 on 2026-06-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propiedad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='dias_duracion',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='fecha_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='prioridad_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
