# Generated by Django 5.2.13 on 2026-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_inmueble_url_video_youtube_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='area',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Área en m²'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='banos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Baños'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='habitaciones',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Habitaciones'),
        ),
    ]
