# Generated by Django 5.2.13 on 2026-05-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.AddField(
            model_name='plan',
            name='nombre',
            field=models.CharField(default='Plan Especial', max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_images',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_properties',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default='Plan Especial', max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
