# Generated by Django 5.2.13 on 2026-06-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='wompi_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Transacción de Wompi'),
        ),
        migrations.AddField(
            model_name='pago',
            name='wompi_payment_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado del Pago en Wompi'),
        ),
        migrations.AddField(
            model_name='pago',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Transacción de Wompi'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En Proceso'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito'), ('pse', 'PSE'), ('nequi', 'Nequi'), ('wompi', 'Wompi')], default='wompi', max_length=20),
        ),
    ]
